### ISSUE TITLE
Save to folder as game name rather than Title ID

### ISSUE THREAD

**Issue by VashTS000** [r4dius/Iso2God#2]
Would this be possible to add? I'd prefer the game name instead of the Title ID as the folder name when the conversion is done

**Comment by r4dius** [comment]
Have a try : https://github.com/r4dius/Iso2God/releases/tag/1.3.8
Now you can use a checkbox in Add ISO / Settings menu to use title name as directory name
It should check the title for caracters that can't be used in a directory name and remove them, if directory name is empty after this replacement it should fallback to ID as directory name,
I did not test in on the console nor the FTP transfer, please consider this a not well tested at all, let me know in case of a problem

**Comment by r4dius** [comment]
New version is released, added 4 "GOD layouts" for the output, should fit you need
