### ISSUE TITLE
[Request] Auto delete ISO after conversion?

### ISSUE THREAD

**Issue by Coolumin** [r4dius/Iso2God#3]
I like to keep all my games in GOD format for consistancy, but since ISO2GOD currently doesn't have an option of automatically deleting the original ISO you're converting, I have to account for a lot of extra space being available on my hard drive in order to batch convert all of my games. It would be nice if there was an option to auto delete the source ISO after conversion.

This is probably an odd request, but is it also possible to add .zip support too? A bit like how [this app](https://github.com/sahlberg/pop-fe) does it, where it automatically extracts the zip file before conversion.

**Comment by blahpr** [comment]
Here You Go -> https://github.com/blahpr/Iso2God/releases/latest

**Comment by r4dius** [comment]
Deletion is added in last release
