### ISSUE TITLE
OG Xbox games w/ video partition ("Redump format") don't seem to be supported 

### ISSUE THREAD

**Issue by Coolumin** [r4dius/Iso2God#4]
Whenever you attempt to add an OG Xbox ISO that has the original video partition, the program is unable to locate the executable file like in the following image. If you truncate the video partition or do a full conversion to an "XISO" with something like xdvdfs, it will then become compatible. 

![image](https://github.com/user-attachments/assets/bf3f77a4-7b08-4b51-8074-9f23175ddde4)

**Comment by Coolumin** [comment]
This functionality has actually been implimented in iso2god-rs: https://github.com/iliazeus/iso2god-rs/commit/4e52ce3edd18ffc41bbb568fdac1f3f8c42129ca

**Comment by r4dius** [comment]
Thanks will give it a look too :)

**Comment by r4dius** [comment]
Added in last release
