### ISSUE TITLE
(Request) Make A New Folder Before The Title ID of The Game

### ISSUE THREAD

**Issue by dominater01** [r4dius/Iso2God#5]
is there a way for you to not have it rename the title id to game name but instead make a new folder with the game name and put the title id inside of it that would be much better for me

**Comment by r4dius** [comment]
I'll be looking for a way to allow for custom output paths

**Comment by dominater01** [comment]
it'd also be nice if the folder names were based on the iso name instead of the internal names as those are mostly wrong at least with my iso's

**Comment by r4dius** [comment]
It will, I'm adding a list of "correct" names that's used in place of the names from the game files :)

**Comment by r4dius** [comment]
Done in 1.5.0

**Comment by dominater01** [comment]
> Done in 1.5.0

its alot better now, thanks :)
