### ISSUE TITLE
[Request] Pull game info from XboxUnity & MobCat's database

### ISSUE THREAD

**Issue by Coolumin** [r4dius/Iso2God#9]
A lot of executibles in Xbox 360 games have weird internal names instead of the proper ones used in the Marketplace, so it would be useful if there was a setting to pull them from online databases like XboxUnity instead. 

[iso2god-rs](https://github.com/iliazeus/iso2god-rs) is an example of a tool that already uses XboxUnity for game names.

**Comment by r4dius** [comment]
I like this idea, I would prefer to have the list in a local file since it is now fixed.
There's one available here, I'll have a look :)

**Comment by Coolumin** [comment]
As an addendum, I have noticed ISO2GOD not being able to pull the XBE thumbnails from a few games like GTA San Andreas. In those situations, maybe they could be pulled from MobCat or something, since they appear to have a (almost?) complete archive of every game icon/thumbnail used for Xbox Classic games.

**Comment by r4dius** [comment]
I just tested this, in gta specifically there are 2 images in the xbe, one is the "thumbnail" and the other one is the "save file" icon or something like that, by default iso2god uses the "save file" icon if available,
the 2 files are not in the same XPR image format for some reason, the "thumbnail" one is DXT1 and the "save game" icon is ARGB which is supposed to be supported by iso2god but there may be multiple formats for this I guess and iso2god only has one ARBG

I found this tool that support lots of them https://github.com/Ernegien/UIXTool/blob/main/src/Formats/Xpr/XprResource.cs but image format code it just over my mind, it'd be a pain for me to figure out what's needed as a simple fix rather than using multiple functions from this project,

So for now I changed the order so that the "thumbnail" icon is preferred by default but I can't guarantee some other games won't have the same format problem with "thumbnail" icon, I only used dead or alive ultimate and gta as isos to test so it'll need some testing from you 🤣

I tested the title renaming thing using a list file and I'm using the MobCat list for og xbox as it looked like the best one I could find, I need to compare multiple xbox 360 lists to find the best and clean a bit before release

**Comment by Coolumin** [comment]
> I just tested this, in gta specifically there are 2 images in the xbe, one is the "thumbnail" and the other one is the "save file" icon or something like that, by default iso2god uses the "save file" icon if available, the 2 files are not in the same XPR image format for some reason, the "thumbnail" one is DXT1 and the "save game" icon is ARGB which is supposed to be supported by iso2god but there may be multiple formats for this I guess and iso2god only has one ARBG
> 
> I found this tool that support lots of them https://github.com/Ernegien/UIXTool/blob/main/src/Formats/Xpr/XprResource.cs but image format code it just over my mind, it'd be a pain for me to figure out what's needed as a simple fix rather than using multiple functions from this project,
> 
> So for now I changed the order so that the "thumbnail" icon is preferred by default but I can't guarantee some other games won't have the same format problem with "thumbnail" icon, I only used dead or alive ultimate and gta as isos to test so it'll need some testing from you 🤣
> 
> I tested the title renaming thing using a list file and I'm using the MobCat list for og xbox as it looked like the best one I could find, I need to compare multiple xbox 360 lists to find the best and clean a bit before release

Awesome! As for other games with a unsupported thumbnail, I saw that True Crime: New York City didn't work by default with the program.

**Comment by r4dius** [comment]
Yep icon is still fcked up in true crime, it'd need some code port to fix, btw are those icons visible anywhere in the console 😂 ?
If not it may not "need" fix, the other blocking errors should be fixed

**Comment by Coolumin** [comment]
> Yep icon is still fcked up in true crime, it'd need some code port to fix, btw are those icons visible anywhere in the console 😂 ? If not it may not "need" fix, the other blocking errors should be fixed

They're visible if you're using the game libraries in old official dashboards before Metro. The storage settings in Microsoft's dashboard also shows icons for any STFS/SVOD content.

**Comment by r4dius** [comment]
Yeah I don't like it either 😕, I borrowed the code from https://github.com/Ernegien/UIXTool/blob/main/src/Formats/Xpr/XprResource.cs and it looks ok for gta now (I can't find the true crime file I tested before), here's a build you can test please let me know if you see other games with a problem as this code only fixes 1 format and I have no idea if the other ones are used in xbox og xbe too
[iso2god-1.40-test-1.zip](https://github.com/user-attachments/files/17416274/iso2god-1.40-test-1.zip)

**Comment by Coolumin** [comment]
> Yeah I don't like it either 😕, I borrowed the code from https://github.com/Ernegien/UIXTool/blob/main/src/Formats/Xpr/XprResource.cs and it looks ok for gta now (I can't find the true crime file I tested before), here's a build you can test please let me know if you see other games with a problem as this code only fixes 1 format and I have no idea if the other ones are used in xbox og xbe too [iso2god-1.40-test-1.zip](https://github.com/user-attachments/files/17416274/iso2god-1.40-test-1.zip)

Yeah, this version of the program gets the icon for TC: NYC now. Really great to see the drag and dropping and "Redump" XGD1's working properly now too.

**Comment by Coolumin** [comment]
Well darn, it seems like 4947000B has an iffy icon too. 
![image](https://github.com/user-attachments/assets/2097291c-b85f-4bd3-9261-4d1999017e46)

**Comment by r4dius** [comment]
For some reason the game has thumbnail image + savegame icon and both are the same,
iso2god expects savegame iso to be 64x64 and here it's 128x128,
not sure why iso2god was not reading image size from headers has the code is there, I change it so it use it,
I changed lots of other stuff so need to test it before release

**Comment by r4dius** [comment]
New version is released, please have a look if everything is ok ?

**Comment by Coolumin** [comment]
> New version is released, please have a look if everything is ok ?

Works pretty darn good so far, thank you!
